freebsd_instance:
  image_family: freebsd-15-0-snap
task:
  name: cargo test (stable)
  env:
    HOME: /tmp # cargo needs it
  install_script: |
    pkg install -y rust
    pkg install -y cmake
    pkg install -y git
  build_script: |
    git submodule update --init
    cargo build --all
  test_script: cargo test --all --all-targets
  
