[package]
name = "snmalloc_rs"
version = "0.0.0"
edition = "2024"
publish = false
homepage = "https://github.com/microsoft/snmalloc"
repository = "https://github.com/microsoft/snmalloc"


[lib]
path = "lib.rs"

[dependencies]
libc = "0.2.172"